- hosts: all
  roles:
    - role: ensure-build-essential
      become: yes
    - role: ensure-zip
      become: yes
    - role: ensure-nodejs-fork
      vars:
        node_version: 20
      become: yes
    - role: ensure-cws-upload
      version: "2.1.0"
      become: yes
    - role: ensure-bazelisk
      vars:
        bazelisk_version: v1.27.0
