- name: Install pnpm
  ansible.builtin.command: npm install -g pnpm@9
  args:
    chdir: "{{ zuul.project.src_dir }}"
  become: yes

- name: Ouptut pnpm version
  ansible.builtin.command: pnpm --version

- name: Build extension
  make:
    chdir: "{{ zuul.project.src_dir }}"
    target: "{{ make_target }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/go/bin:/usr/local/go/bin:{{ ansible_env.PATH }}"
